DROP TABLE EXAMEN_X_CATEGORIA CASCADE CONSTRAINTS;

CREATE TABLE EXAMEN_X_CATEGORIA
(
	IDEEXAMENXCATEGORIA  NUMBER(8), 
	IDEEXAMEN            NUMBER(8), 
	IDECATEGORIA         NUMBER(8), 
	ESTACTIVO            VARCHAR2(1), 
	USRCREACION          VARCHAR2(15), 
	FECCREACION          DATE, 
	USRMODIFICA          VARCHAR2(15), 
	FECMODIFICA          DATE 
)
;

COMMENT ON TABLE EXAMEN_X_CATEGORIA IS 'Tabla de categorias por examen';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.IDEEXAMENXCATEGORIA  IS 'Identificador de la tabla';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.IDEEXAMEN            IS 'Identificador foraneo de la Tabla Examen';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.IDECATEGORIA         IS 'Identificador foraneo de la Tabla Categoria';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.ESTACTIVO            IS 'Indicador de estado A(activo) y I(inactivo)';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.USRCREACION          IS 'Usuario de creacion del registro';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.FECCREACION          IS 'Fecha de creacion del registro';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.USRMODIFICA          IS 'Usuario de modificacion';
COMMENT ON COLUMN EXAMEN_X_CATEGORIA.FECMODIFICA          IS 'Fecha de modificacion';


ALTER TABLE EXAMEN_X_CATEGORIA ADD CONSTRAINT EXAMEN_CATEGORIA_PK	PRIMARY KEY (IDEEXAMENXCATEGORIA);

ALTER TABLE EXAMEN_X_CATEGORIA ADD CONSTRAINT EXAM_X_CAT_CATEGORIA_FK FOREIGN KEY (IDECATEGORIA) REFERENCES CATEGORIA (IDECATEGORIA);

ALTER TABLE EXAMEN_X_CATEGORIA ADD CONSTRAINT EXAM_X_CAT_EXAMEN_FK_ FOREIGN KEY (IDEEXAMEN) REFERENCES EXAMEN (IDEEXAMEN);


ALTER TABLE EXAMEN_X_CATEGORIA MODIFY IDEEXAMEN CONSTRAINT EXAM_X_CAT_IDEEXAMEN_NN NOT NULL ;

ALTER TABLE EXAMEN_X_CATEGORIA MODIFY IDECATEGORIA CONSTRAINT EXAM_X_CAT_IDECATEGORIA_NN NOT NULL ;

ALTER TABLE EXAMEN_X_CATEGORIA MODIFY ESTACTIVO CONSTRAINT EXAM_X_CAT_ESTACTIVO_NN NOT NULL ;
