DROP TABLE EXAMEN CASCADE CONSTRAINTS;

CREATE TABLE EXAMEN
(
  IDEEXAMEN        NUMBER(8), 
  IDESEDE          NUMBER(8), 
  ESTREGISTRO      VARCHAR2(3), 
  NOMEXAMEN        VARCHAR2(20), 
  DESCEXAMEN       VARCHAR2(150), 
  TIPEXAMEN        VARCHAR2(3),
  ESTACTIVO        VARCHAR2(1), 
  USRCREACION      VARCHAR2(15), 
  FECCREACION      DATE, 
  USRMODIFICACION  VARCHAR2(15), 
  FECMODIFICACION  DATE 
)
;

COMMENT ON TABLE EXAMEN IS 'Tabla de exámenes';
COMMENT ON COLUMN EXAMEN.IDEEXAMEN        IS 'Identificador de la Tabla.';
COMMENT ON COLUMN EXAMEN.IDESEDE          IS 'Identificador de la tabla sede';
COMMENT ON COLUMN EXAMEN.ESTREGISTRO      IS 'Estado del registro.';
COMMENT ON COLUMN EXAMEN.NOMEXAMEN        IS 'Nombre del Examen.';
COMMENT ON COLUMN EXAMEN.DESCEXAMEN       IS 'Descripcion del Examen.';
COMMENT ON COLUMN EXAMEN.TIPEXAMEN        IS 'Tipo de Examen. Identificador foraneo de Tabla General.';
COMMENT ON COLUMN EXAMEN.ESTACTIVO        IS 'Indicador de estado A(Activo), I(Inactivo).';
COMMENT ON COLUMN EXAMEN.USRCREACION      IS 'Usuario Creacion del registro.';
COMMENT ON COLUMN EXAMEN.FECCREACION      IS 'Fecha de creacion del registro.';
COMMENT ON COLUMN EXAMEN.USRMODIFICACION  IS 'Usuario de modificacion del registro.';
COMMENT ON COLUMN EXAMEN.FECMODIFICACION  IS 'Fecha de modificacion.';

ALTER TABLE EXAMEN ADD CONSTRAINT EXAMEN_PK PRIMARY KEY (IDEEXAMEN);


ALTER TABLE EXAMEN MODIFY NOMEXAMEN CONSTRAINT EXAMEN_NOMEXAMEN_NN NOT NULL ;

ALTER TABLE EXAMEN MODIFY DESCEXAMEN CONSTRAINT EXAMEN_DESCEXAMEN_NN NOT NULL ;

ALTER TABLE EXAMEN MODIFY TIPEXAMEN CONSTRAINT EXAMEN_TIPEXAMEN_NN NOT NULL ;

ALTER TABLE EXAMEN MODIFY ESTACTIVO CONSTRAINT EXAMEN_ESTACTIVO_NN NOT NULL ;
