DROP TABLE RECL_PERS_EXAM_CAT CASCADE CONSTRAINTS
;
CREATE TABLE RECL_PERS_EXAM_CAT
(
  IDERECLPERSOEXAMNCAT    NUMBER(8),
  IDERECLUTAPERSONA       NUMBER(8),
  IDERECLUPERSOEXAMEN     NUMBER(8),
  IDEEXAMENXCATEGORIA     NUMBER(8),
  ESTADO                  VARCHAR(3), 
  NOTAEXAMENCATEG         NUMBER(2),
  ESTACTIVO               VARCHAR(1),
  USRCREACION             VARCHAR(15),
  FECCREACION             DATE,
  USRMODIFICA             VARCHAR(15),
  FECMODIFICA             DATE
)
;

COMMENT ON TABLE RECL_PERS_EXAM_CAT IS 'Tabla que registra las categorias dentro del examen que rendira el postulante';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.IDERECLPERSOEXAMNCAT  IS 'Identificador la categoria dentro del examen que rendira el postulante';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.IDERECLUPERSOEXAMEN   IS 'identificador de la tabla RECLUTAMIENTO_PERSONA_EXAMEN';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.IDEEXAMENXCATEGORIA   IS 'Identificador del examen x categoría';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.ESTADO                IS 'estado de la categoria - pendiente, evaluado';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.NOTAEXAMENCATEG       IS 'Puntaje total obtenido por categoria por la persona';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.USRMODIFICA           IS 'Usuario que creó el registro';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.FECCREACION           IS 'Fecha de creación del registro';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.USRMODIFICA           IS 'Usuario que modificó el registro';

COMMENT ON COLUMN RECL_PERS_EXAM_CAT.FECMODIFICA           IS 'Fecha de modificación del registro';


ALTER TABLE RECL_PERS_EXAM_CAT ADD CONSTRAINT RECL_PERS_EXAM_CAT_PK 
  PRIMARY KEY (IDERECLPERSOEXAMNCAT)  USING INDEX ;

ALTER TABLE RECL_PERS_EXAM_CAT ADD CONSTRAINT RE_PER_EX_CAT_RECPER_EXAMEN_FK 
  FOREIGN KEY (IDERECLUPERSOEXAMEN) REFERENCES RECLU_PERSO_EXAMEN(IDERECLUPERSOEXAMEN);
  
ALTER TABLE RECL_PERS_EXAM_CAT ADD CONSTRAINT RECLPERS_EXAMCAT_EXAMXCAT_FK 
  FOREIGN KEY (IDEEXAMENXCATEGORIA) REFERENCES EXAMEN_X_CATEGORIA(IDEEXAMENXCATEGORIA);
  
ALTER TABLE RECL_PERS_EXAM_CAT ADD CONSTRAINT RECLPERS_EXAMCAT_RECLPERS_FK 
  FOREIGN KEY (IDERECLUTAPERSONA) REFERENCES RECLUTAMIENTO_PERSONA(IDERECLUTAPERSONA);


 