DROP TABLE RECLU_PERSO_ALTERNATIVA CASCADE CONSTRAINTS
;
CREATE TABLE RECLU_PERSO_ALTERNATIVA
(
  IDERECLUPERSOALTERNATIVA  NUMBER(8), 
  IDERECLUTAPERSONA         NUMBER(8),
  IDERECLUPERSOCRITERIO     NUMBER(8), 
  IDEALTERNATIVA            NUMBER(8), 
  USRCREACION               VARCHAR2(15), 
  FECCREACION               DATE, 
  USRMODIFICA               VARCHAR2(15), 
  FECMODIFICA               DATE 
)
;

COMMENT ON TABLE RECLU_PERSO_ALTERNATIVA IS 'Tabla de alternativas seleccionadas por la persona en el examen';

COMMENT ON COLUMN RECLU_PERSO_ALTERNATIVA.IDERECLUPERSOALTERNATIVA  IS 'Identificador de criterios repondidos por el postulante';

COMMENT ON COLUMN RECLU_PERSO_ALTERNATIVA.IDERECLUPERSOCRITERIO     IS 'Identificador del criterio contestado por el postulante';

COMMENT ON COLUMN RECLU_PERSO_ALTERNATIVA.IDEALTERNATIVA            IS 'Identificador de la alternativa';

COMMENT ON COLUMN RECLU_PERSO_ALTERNATIVA.USRCREACION               IS 'Usuario que creó el registro';

COMMENT ON COLUMN RECLU_PERSO_ALTERNATIVA.FECCREACION               IS 'Fecha de creación del registro';

COMMENT ON COLUMN RECLU_PERSO_ALTERNATIVA.USRMODIFICA               IS 'Usuario que modificó el registro';

COMMENT ON COLUMN RECLU_PERSO_ALTERNATIVA.FECMODIFICA               IS 'Fecha de modificación del registro';


ALTER TABLE RECLU_PERSO_ALTERNATIVA ADD CONSTRAINT RECLU_PERSO_ALTERNATIVA_PK 
  PRIMARY KEY (IDERECLUPERSOALTERNATIVA) USING INDEX;

ALTER TABLE RECLU_PERSO_ALTERNATIVA ADD CONSTRAINT RECL_PERS_AL_IDERECLPERCRIT_FK 
  FOREIGN KEY (IDERECLUPERSOCRITERIO) REFERENCES RECLU_PERSO_CRITERIO (IDERECLUPERSOCRITERIO);           
 
 ALTER TABLE RECLU_PERSO_ALTERNATIVA ADD CONSTRAINT RECL_PERS_AL_IDEALTERNA_FK 
  FOREIGN KEY (IDEALTERNATIVA) REFERENCES ALTERNATIVA (IDEALTERNATIVA);
  
  
   ALTER TABLE RECLU_PERSO_ALTERNATIVA ADD CONSTRAINT RECL_PERS_AL_IDERECLPERSO_FK 
  FOREIGN KEY (IDERECLUTAPERSONA) REFERENCES RECLUTAMIENTO_PERSONA (IDERECLUTAPERSONA);