//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace SanPablo.Reclutador.Web.Reportes.Intranet {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DtReporteSeleccion")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DtReporteSeleccion : global::System.Data.DataSet {
        
        private DtReporteSeleccionDataTable tableDtReporteSeleccion;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DtReporteSeleccion() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DtReporteSeleccion(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DtReporteSeleccion"] != null)) {
                    base.Tables.Add(new DtReporteSeleccionDataTable(ds.Tables["DtReporteSeleccion"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DtReporteSeleccionDataTable _DtReporteSeleccion {
            get {
                return this.tableDtReporteSeleccion;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DtReporteSeleccion cln = ((DtReporteSeleccion)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DtReporteSeleccion"] != null)) {
                    base.Tables.Add(new DtReporteSeleccionDataTable(ds.Tables["DtReporteSeleccion"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableDtReporteSeleccion = ((DtReporteSeleccionDataTable)(base.Tables["DtReporteSeleccion"]));
            if ((initTable == true)) {
                if ((this.tableDtReporteSeleccion != null)) {
                    this.tableDtReporteSeleccion.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DtReporteSeleccion";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DtReporteSeleccion.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDtReporteSeleccion = new DtReporteSeleccionDataTable();
            base.Tables.Add(this.tableDtReporteSeleccion);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerialize_DtReporteSeleccion() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DtReporteSeleccion ds = new DtReporteSeleccion();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void DtReporteSeleccionRowChangeEventHandler(object sender, DtReporteSeleccionRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DtReporteSeleccionDataTable : global::System.Data.TypedTableBase<DtReporteSeleccionRow> {
            
            private global::System.Data.DataColumn columnIDESOLREQPERSONAL;
            
            private global::System.Data.DataColumn columnESTADO_PROCESO;
            
            private global::System.Data.DataColumn columnFECHA_REQUERIMIENTO;
            
            private global::System.Data.DataColumn columnSEDE;
            
            private global::System.Data.DataColumn columnDESDEPENDENCIA;
            
            private global::System.Data.DataColumn columnDESDEPARTAMENTO;
            
            private global::System.Data.DataColumn columnDESAREA;
            
            private global::System.Data.DataColumn columnCARGO;
            
            private global::System.Data.DataColumn columnJEFE;
            
            private global::System.Data.DataColumn columnTIPSOL;
            
            private global::System.Data.DataColumn columnREEMPLAZA_A;
            
            private global::System.Data.DataColumn columnFECREEMPLAZO;
            
            private global::System.Data.DataColumn columnMOTIVOREEMPLAZO;
            
            private global::System.Data.DataColumn columnANALISTA_RESP;
            
            private global::System.Data.DataColumn columnP_INGRESA;
            
            private global::System.Data.DataColumn columnFECHA_CONTRATACION;
            
            private global::System.Data.DataColumn columnDIAS;
            
            private global::System.Data.DataColumn columnNUMDOCUMENTO;
            
            private global::System.Data.DataColumn columnFONO;
            
            private global::System.Data.DataColumn columnOBSPSICOLOGO;
            
            private global::System.Data.DataColumn columnOBSENTREVISTA;
            
            private global::System.Data.DataColumn columnFECSUCESO;
            
            private global::System.Data.DataColumn columnMOTIVOCIERRE;
            
            private global::System.Data.DataColumn columnIDESEDE;
            
            private global::System.Data.DataColumn columnUSRSUCESO;
            
            private global::System.Data.DataColumn columnTIPETAPA;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DtReporteSeleccionDataTable() {
                this.TableName = "DtReporteSeleccion";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal DtReporteSeleccionDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected DtReporteSeleccionDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IDESOLREQPERSONALColumn {
                get {
                    return this.columnIDESOLREQPERSONAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ESTADO_PROCESOColumn {
                get {
                    return this.columnESTADO_PROCESO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FECHA_REQUERIMIENTOColumn {
                get {
                    return this.columnFECHA_REQUERIMIENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SEDEColumn {
                get {
                    return this.columnSEDE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DESDEPENDENCIAColumn {
                get {
                    return this.columnDESDEPENDENCIA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DESDEPARTAMENTOColumn {
                get {
                    return this.columnDESDEPARTAMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DESAREAColumn {
                get {
                    return this.columnDESAREA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CARGOColumn {
                get {
                    return this.columnCARGO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn JEFEColumn {
                get {
                    return this.columnJEFE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TIPSOLColumn {
                get {
                    return this.columnTIPSOL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn REEMPLAZA_AColumn {
                get {
                    return this.columnREEMPLAZA_A;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FECREEMPLAZOColumn {
                get {
                    return this.columnFECREEMPLAZO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MOTIVOREEMPLAZOColumn {
                get {
                    return this.columnMOTIVOREEMPLAZO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ANALISTA_RESPColumn {
                get {
                    return this.columnANALISTA_RESP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn P_INGRESAColumn {
                get {
                    return this.columnP_INGRESA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FECHA_CONTRATACIONColumn {
                get {
                    return this.columnFECHA_CONTRATACION;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DIASColumn {
                get {
                    return this.columnDIAS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NUMDOCUMENTOColumn {
                get {
                    return this.columnNUMDOCUMENTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FONOColumn {
                get {
                    return this.columnFONO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OBSPSICOLOGOColumn {
                get {
                    return this.columnOBSPSICOLOGO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn OBSENTREVISTAColumn {
                get {
                    return this.columnOBSENTREVISTA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FECSUCESOColumn {
                get {
                    return this.columnFECSUCESO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MOTIVOCIERREColumn {
                get {
                    return this.columnMOTIVOCIERRE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn IDESEDEColumn {
                get {
                    return this.columnIDESEDE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn USRSUCESOColumn {
                get {
                    return this.columnUSRSUCESO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TIPETAPAColumn {
                get {
                    return this.columnTIPETAPA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DtReporteSeleccionRow this[int index] {
                get {
                    return ((DtReporteSeleccionRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DtReporteSeleccionRowChangeEventHandler DtReporteSeleccionRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DtReporteSeleccionRowChangeEventHandler DtReporteSeleccionRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DtReporteSeleccionRowChangeEventHandler DtReporteSeleccionRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event DtReporteSeleccionRowChangeEventHandler DtReporteSeleccionRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddDtReporteSeleccionRow(DtReporteSeleccionRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DtReporteSeleccionRow AddDtReporteSeleccionRow(
                        string IDESOLREQPERSONAL, 
                        string ESTADO_PROCESO, 
                        string FECHA_REQUERIMIENTO, 
                        string SEDE, 
                        string DESDEPENDENCIA, 
                        string DESDEPARTAMENTO, 
                        string DESAREA, 
                        string CARGO, 
                        string JEFE, 
                        string TIPSOL, 
                        string REEMPLAZA_A, 
                        string FECREEMPLAZO, 
                        string MOTIVOREEMPLAZO, 
                        string ANALISTA_RESP, 
                        string P_INGRESA, 
                        string FECHA_CONTRATACION, 
                        string DIAS, 
                        string NUMDOCUMENTO, 
                        string FONO, 
                        string OBSPSICOLOGO, 
                        string OBSENTREVISTA, 
                        string FECSUCESO, 
                        string MOTIVOCIERRE, 
                        string IDESEDE, 
                        string USRSUCESO, 
                        string TIPETAPA) {
                DtReporteSeleccionRow rowDtReporteSeleccionRow = ((DtReporteSeleccionRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IDESOLREQPERSONAL,
                        ESTADO_PROCESO,
                        FECHA_REQUERIMIENTO,
                        SEDE,
                        DESDEPENDENCIA,
                        DESDEPARTAMENTO,
                        DESAREA,
                        CARGO,
                        JEFE,
                        TIPSOL,
                        REEMPLAZA_A,
                        FECREEMPLAZO,
                        MOTIVOREEMPLAZO,
                        ANALISTA_RESP,
                        P_INGRESA,
                        FECHA_CONTRATACION,
                        DIAS,
                        NUMDOCUMENTO,
                        FONO,
                        OBSPSICOLOGO,
                        OBSENTREVISTA,
                        FECSUCESO,
                        MOTIVOCIERRE,
                        IDESEDE,
                        USRSUCESO,
                        TIPETAPA};
                rowDtReporteSeleccionRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDtReporteSeleccionRow);
                return rowDtReporteSeleccionRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                DtReporteSeleccionDataTable cln = ((DtReporteSeleccionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DtReporteSeleccionDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnIDESOLREQPERSONAL = base.Columns["IDESOLREQPERSONAL"];
                this.columnESTADO_PROCESO = base.Columns["ESTADO_PROCESO"];
                this.columnFECHA_REQUERIMIENTO = base.Columns["FECHA_REQUERIMIENTO"];
                this.columnSEDE = base.Columns["SEDE"];
                this.columnDESDEPENDENCIA = base.Columns["DESDEPENDENCIA"];
                this.columnDESDEPARTAMENTO = base.Columns["DESDEPARTAMENTO"];
                this.columnDESAREA = base.Columns["DESAREA"];
                this.columnCARGO = base.Columns["CARGO"];
                this.columnJEFE = base.Columns["JEFE"];
                this.columnTIPSOL = base.Columns["TIPSOL"];
                this.columnREEMPLAZA_A = base.Columns["REEMPLAZA_A"];
                this.columnFECREEMPLAZO = base.Columns["FECREEMPLAZO"];
                this.columnMOTIVOREEMPLAZO = base.Columns["MOTIVOREEMPLAZO"];
                this.columnANALISTA_RESP = base.Columns["ANALISTA_RESP"];
                this.columnP_INGRESA = base.Columns["P_INGRESA"];
                this.columnFECHA_CONTRATACION = base.Columns["FECHA_CONTRATACION"];
                this.columnDIAS = base.Columns["DIAS"];
                this.columnNUMDOCUMENTO = base.Columns["NUMDOCUMENTO"];
                this.columnFONO = base.Columns["FONO"];
                this.columnOBSPSICOLOGO = base.Columns["OBSPSICOLOGO"];
                this.columnOBSENTREVISTA = base.Columns["OBSENTREVISTA"];
                this.columnFECSUCESO = base.Columns["FECSUCESO"];
                this.columnMOTIVOCIERRE = base.Columns["MOTIVOCIERRE"];
                this.columnIDESEDE = base.Columns["IDESEDE"];
                this.columnUSRSUCESO = base.Columns["USRSUCESO"];
                this.columnTIPETAPA = base.Columns["TIPETAPA"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnIDESOLREQPERSONAL = new global::System.Data.DataColumn("IDESOLREQPERSONAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDESOLREQPERSONAL);
                this.columnESTADO_PROCESO = new global::System.Data.DataColumn("ESTADO_PROCESO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnESTADO_PROCESO);
                this.columnFECHA_REQUERIMIENTO = new global::System.Data.DataColumn("FECHA_REQUERIMIENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFECHA_REQUERIMIENTO);
                this.columnSEDE = new global::System.Data.DataColumn("SEDE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSEDE);
                this.columnDESDEPENDENCIA = new global::System.Data.DataColumn("DESDEPENDENCIA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDESDEPENDENCIA);
                this.columnDESDEPARTAMENTO = new global::System.Data.DataColumn("DESDEPARTAMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDESDEPARTAMENTO);
                this.columnDESAREA = new global::System.Data.DataColumn("DESAREA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDESAREA);
                this.columnCARGO = new global::System.Data.DataColumn("CARGO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCARGO);
                this.columnJEFE = new global::System.Data.DataColumn("JEFE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJEFE);
                this.columnTIPSOL = new global::System.Data.DataColumn("TIPSOL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTIPSOL);
                this.columnREEMPLAZA_A = new global::System.Data.DataColumn("REEMPLAZA_A", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREEMPLAZA_A);
                this.columnFECREEMPLAZO = new global::System.Data.DataColumn("FECREEMPLAZO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFECREEMPLAZO);
                this.columnMOTIVOREEMPLAZO = new global::System.Data.DataColumn("MOTIVOREEMPLAZO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMOTIVOREEMPLAZO);
                this.columnANALISTA_RESP = new global::System.Data.DataColumn("ANALISTA_RESP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnANALISTA_RESP);
                this.columnP_INGRESA = new global::System.Data.DataColumn("P_INGRESA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnP_INGRESA);
                this.columnFECHA_CONTRATACION = new global::System.Data.DataColumn("FECHA_CONTRATACION", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFECHA_CONTRATACION);
                this.columnDIAS = new global::System.Data.DataColumn("DIAS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIAS);
                this.columnNUMDOCUMENTO = new global::System.Data.DataColumn("NUMDOCUMENTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNUMDOCUMENTO);
                this.columnFONO = new global::System.Data.DataColumn("FONO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFONO);
                this.columnOBSPSICOLOGO = new global::System.Data.DataColumn("OBSPSICOLOGO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOBSPSICOLOGO);
                this.columnOBSENTREVISTA = new global::System.Data.DataColumn("OBSENTREVISTA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOBSENTREVISTA);
                this.columnFECSUCESO = new global::System.Data.DataColumn("FECSUCESO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFECSUCESO);
                this.columnMOTIVOCIERRE = new global::System.Data.DataColumn("MOTIVOCIERRE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMOTIVOCIERRE);
                this.columnIDESEDE = new global::System.Data.DataColumn("IDESEDE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDESEDE);
                this.columnUSRSUCESO = new global::System.Data.DataColumn("USRSUCESO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUSRSUCESO);
                this.columnTIPETAPA = new global::System.Data.DataColumn("TIPETAPA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTIPETAPA);
                this.ExtendedProperties.Add("Generator_TablePropName", "_DtReporteSeleccion");
                this.ExtendedProperties.Add("Generator_UserTableName", "DtReporteSeleccion");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DtReporteSeleccionRow NewDtReporteSeleccionRow() {
                return ((DtReporteSeleccionRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DtReporteSeleccionRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(DtReporteSeleccionRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DtReporteSeleccionRowChanged != null)) {
                    this.DtReporteSeleccionRowChanged(this, new DtReporteSeleccionRowChangeEvent(((DtReporteSeleccionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DtReporteSeleccionRowChanging != null)) {
                    this.DtReporteSeleccionRowChanging(this, new DtReporteSeleccionRowChangeEvent(((DtReporteSeleccionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DtReporteSeleccionRowDeleted != null)) {
                    this.DtReporteSeleccionRowDeleted(this, new DtReporteSeleccionRowChangeEvent(((DtReporteSeleccionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DtReporteSeleccionRowDeleting != null)) {
                    this.DtReporteSeleccionRowDeleting(this, new DtReporteSeleccionRowChangeEvent(((DtReporteSeleccionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveDtReporteSeleccionRow(DtReporteSeleccionRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DtReporteSeleccion ds = new DtReporteSeleccion();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DtReporteSeleccionDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class DtReporteSeleccionRow : global::System.Data.DataRow {
            
            private DtReporteSeleccionDataTable tableDtReporteSeleccion;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal DtReporteSeleccionRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDtReporteSeleccion = ((DtReporteSeleccionDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IDESOLREQPERSONAL {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.IDESOLREQPERSONALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IDESOLREQPERSONAL\' in table \'DtReporteSeleccion\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.IDESOLREQPERSONALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ESTADO_PROCESO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.ESTADO_PROCESOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ESTADO_PROCESO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.ESTADO_PROCESOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FECHA_REQUERIMIENTO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.FECHA_REQUERIMIENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FECHA_REQUERIMIENTO\' in table \'DtReporteSeleccion\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.FECHA_REQUERIMIENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SEDE {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.SEDEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SEDE\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.SEDEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DESDEPENDENCIA {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.DESDEPENDENCIAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DESDEPENDENCIA\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.DESDEPENDENCIAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DESDEPARTAMENTO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.DESDEPARTAMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DESDEPARTAMENTO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.DESDEPARTAMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DESAREA {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.DESAREAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DESAREA\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.DESAREAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CARGO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.CARGOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CARGO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.CARGOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string JEFE {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.JEFEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JEFE\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.JEFEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TIPSOL {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.TIPSOLColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TIPSOL\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.TIPSOLColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string REEMPLAZA_A {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.REEMPLAZA_AColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REEMPLAZA_A\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.REEMPLAZA_AColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FECREEMPLAZO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.FECREEMPLAZOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FECREEMPLAZO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.FECREEMPLAZOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MOTIVOREEMPLAZO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.MOTIVOREEMPLAZOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MOTIVOREEMPLAZO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.MOTIVOREEMPLAZOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ANALISTA_RESP {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.ANALISTA_RESPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ANALISTA_RESP\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.ANALISTA_RESPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string P_INGRESA {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.P_INGRESAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'P_INGRESA\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.P_INGRESAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FECHA_CONTRATACION {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.FECHA_CONTRATACIONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FECHA_CONTRATACION\' in table \'DtReporteSeleccion\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.FECHA_CONTRATACIONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DIAS {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.DIASColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIAS\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.DIASColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NUMDOCUMENTO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.NUMDOCUMENTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NUMDOCUMENTO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.NUMDOCUMENTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FONO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.FONOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FONO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.FONOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string OBSPSICOLOGO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.OBSPSICOLOGOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OBSPSICOLOGO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.OBSPSICOLOGOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string OBSENTREVISTA {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.OBSENTREVISTAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OBSENTREVISTA\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.OBSENTREVISTAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FECSUCESO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.FECSUCESOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FECSUCESO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.FECSUCESOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MOTIVOCIERRE {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.MOTIVOCIERREColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MOTIVOCIERRE\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.MOTIVOCIERREColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string IDESEDE {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.IDESEDEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IDESEDE\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.IDESEDEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string USRSUCESO {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.USRSUCESOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'USRSUCESO\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.USRSUCESOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TIPETAPA {
                get {
                    try {
                        return ((string)(this[this.tableDtReporteSeleccion.TIPETAPAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TIPETAPA\' in table \'DtReporteSeleccion\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDtReporteSeleccion.TIPETAPAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIDESOLREQPERSONALNull() {
                return this.IsNull(this.tableDtReporteSeleccion.IDESOLREQPERSONALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIDESOLREQPERSONALNull() {
                this[this.tableDtReporteSeleccion.IDESOLREQPERSONALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsESTADO_PROCESONull() {
                return this.IsNull(this.tableDtReporteSeleccion.ESTADO_PROCESOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetESTADO_PROCESONull() {
                this[this.tableDtReporteSeleccion.ESTADO_PROCESOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFECHA_REQUERIMIENTONull() {
                return this.IsNull(this.tableDtReporteSeleccion.FECHA_REQUERIMIENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFECHA_REQUERIMIENTONull() {
                this[this.tableDtReporteSeleccion.FECHA_REQUERIMIENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSEDENull() {
                return this.IsNull(this.tableDtReporteSeleccion.SEDEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSEDENull() {
                this[this.tableDtReporteSeleccion.SEDEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDESDEPENDENCIANull() {
                return this.IsNull(this.tableDtReporteSeleccion.DESDEPENDENCIAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDESDEPENDENCIANull() {
                this[this.tableDtReporteSeleccion.DESDEPENDENCIAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDESDEPARTAMENTONull() {
                return this.IsNull(this.tableDtReporteSeleccion.DESDEPARTAMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDESDEPARTAMENTONull() {
                this[this.tableDtReporteSeleccion.DESDEPARTAMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDESAREANull() {
                return this.IsNull(this.tableDtReporteSeleccion.DESAREAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDESAREANull() {
                this[this.tableDtReporteSeleccion.DESAREAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCARGONull() {
                return this.IsNull(this.tableDtReporteSeleccion.CARGOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCARGONull() {
                this[this.tableDtReporteSeleccion.CARGOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsJEFENull() {
                return this.IsNull(this.tableDtReporteSeleccion.JEFEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetJEFENull() {
                this[this.tableDtReporteSeleccion.JEFEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTIPSOLNull() {
                return this.IsNull(this.tableDtReporteSeleccion.TIPSOLColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTIPSOLNull() {
                this[this.tableDtReporteSeleccion.TIPSOLColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsREEMPLAZA_ANull() {
                return this.IsNull(this.tableDtReporteSeleccion.REEMPLAZA_AColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetREEMPLAZA_ANull() {
                this[this.tableDtReporteSeleccion.REEMPLAZA_AColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFECREEMPLAZONull() {
                return this.IsNull(this.tableDtReporteSeleccion.FECREEMPLAZOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFECREEMPLAZONull() {
                this[this.tableDtReporteSeleccion.FECREEMPLAZOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMOTIVOREEMPLAZONull() {
                return this.IsNull(this.tableDtReporteSeleccion.MOTIVOREEMPLAZOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMOTIVOREEMPLAZONull() {
                this[this.tableDtReporteSeleccion.MOTIVOREEMPLAZOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsANALISTA_RESPNull() {
                return this.IsNull(this.tableDtReporteSeleccion.ANALISTA_RESPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetANALISTA_RESPNull() {
                this[this.tableDtReporteSeleccion.ANALISTA_RESPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsP_INGRESANull() {
                return this.IsNull(this.tableDtReporteSeleccion.P_INGRESAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetP_INGRESANull() {
                this[this.tableDtReporteSeleccion.P_INGRESAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFECHA_CONTRATACIONNull() {
                return this.IsNull(this.tableDtReporteSeleccion.FECHA_CONTRATACIONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFECHA_CONTRATACIONNull() {
                this[this.tableDtReporteSeleccion.FECHA_CONTRATACIONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDIASNull() {
                return this.IsNull(this.tableDtReporteSeleccion.DIASColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDIASNull() {
                this[this.tableDtReporteSeleccion.DIASColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNUMDOCUMENTONull() {
                return this.IsNull(this.tableDtReporteSeleccion.NUMDOCUMENTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNUMDOCUMENTONull() {
                this[this.tableDtReporteSeleccion.NUMDOCUMENTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFONONull() {
                return this.IsNull(this.tableDtReporteSeleccion.FONOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFONONull() {
                this[this.tableDtReporteSeleccion.FONOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOBSPSICOLOGONull() {
                return this.IsNull(this.tableDtReporteSeleccion.OBSPSICOLOGOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOBSPSICOLOGONull() {
                this[this.tableDtReporteSeleccion.OBSPSICOLOGOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsOBSENTREVISTANull() {
                return this.IsNull(this.tableDtReporteSeleccion.OBSENTREVISTAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetOBSENTREVISTANull() {
                this[this.tableDtReporteSeleccion.OBSENTREVISTAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFECSUCESONull() {
                return this.IsNull(this.tableDtReporteSeleccion.FECSUCESOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFECSUCESONull() {
                this[this.tableDtReporteSeleccion.FECSUCESOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMOTIVOCIERRENull() {
                return this.IsNull(this.tableDtReporteSeleccion.MOTIVOCIERREColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMOTIVOCIERRENull() {
                this[this.tableDtReporteSeleccion.MOTIVOCIERREColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsIDESEDENull() {
                return this.IsNull(this.tableDtReporteSeleccion.IDESEDEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetIDESEDENull() {
                this[this.tableDtReporteSeleccion.IDESEDEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUSRSUCESONull() {
                return this.IsNull(this.tableDtReporteSeleccion.USRSUCESOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUSRSUCESONull() {
                this[this.tableDtReporteSeleccion.USRSUCESOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTIPETAPANull() {
                return this.IsNull(this.tableDtReporteSeleccion.TIPETAPAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTIPETAPANull() {
                this[this.tableDtReporteSeleccion.TIPETAPAColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class DtReporteSeleccionRowChangeEvent : global::System.EventArgs {
            
            private DtReporteSeleccionRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DtReporteSeleccionRowChangeEvent(DtReporteSeleccionRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public DtReporteSeleccionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591