ALTER TABLE CHSPRP.CONOGEN_PERSONA
 DROP PRIMARY KEY CASCADE;

DROP TABLE CHSPRP.CONOGEN_PERSONA CASCADE CONSTRAINTS;

CREATE TABLE CHSPRP.CONOGEN_PERSONA
(
  IDECONOGENPERSONA  NUMBER(8)                  NOT NULL,
  IDEPERSONA         NUMBER(8),
  TIPOCONOCIMIENTO   VARCHAR2(3 CHAR),
  TIPOCONOGENERAL    VARCHAR2(3 CHAR),
  TIPONIVELCONOCI    VARCHAR2(3 CHAR),
  PUNTCONOCI         NUMBER(8),
  USRCREACION        VARCHAR2(15 CHAR),
  FECCREACION        DATE,
  USRMODIFICA        VARCHAR2(15 CHAR),
  FECMODIFICA        DATE
)
TABLESPACE CHSP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CHSPRP.PK_CONOGEN_POSTULANTE ON CHSPRP.CONOGEN_PERSONA
(IDECONOGENPERSONA)
LOGGING
TABLESPACE CHSP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CHSPRP.CONOGEN_PERSONA ADD (
  CONSTRAINT PK_CONOGEN_POSTULANTE
  PRIMARY KEY
  (IDECONOGENPERSONA)
  USING INDEX CHSPRP.PK_CONOGEN_POSTULANTE);

ALTER TABLE CHSPRP.CONOGEN_PERSONA ADD (
  CONSTRAINT FK_CONOGEN_POSTULAN_POSTULANTE 
  FOREIGN KEY (IDEPERSONA) 
  REFERENCES CHSPRP.PERSONA (IDEPERSONA));

