--DROP TABLE CRITERIO CASCADE CONSTRAINTS;
CREATE TABLE CRITERIO
(
  IDECRITERIO      NUMBER(8), 
  TIPMEDICION      VARCHAR2(2), 
  TIPCRITERIO      VARCHAR2(2), 
  TIPMODO          VARCHAR2(2),
  PREGUNTA         VARCHAR2(400),
  TIPCALIFICACION  VARCHAR2(2),
  ORDENIMPRESION   NUMBER(4),
  INDACTIVO        VARCHAR2(1), 
  USRCREACION      VARCHAR2(15), 
  FECCREACION      DATE, 
  USRMODIFICACION  VARCHAR2(15), 
  FECMODIFICACION  DATE 
);

COMMENT ON TABLE CRITERIO IS 'Tabla de datos generales';
COMMENT ON COLUMN CRITERIO.IDECRITERIO      IS 'Identificador de la tabla';
COMMENT ON COLUMN CRITERIO.TIPMEDICION      IS 'Tipo de medicion';
COMMENT ON COLUMN CRITERIO.TIPCRITERIO      IS 'Tipo de criterio';
COMMENT ON COLUMN CRITERIO.TIPMODO          IS 'Tipo de modo';
COMMENT ON COLUMN CRITERIO.PREGUNTA         IS 'Texto Pregunta';
COMMENT ON COLUMN CRITERIO.TIPCALIFICACION  IS 'Tipo de calificacion';
COMMENT ON COLUMN CRITERIO.ORDENIMPRESION   IS 'Orden de impresion';
COMMENT ON COLUMN CRITERIO.INDACTIVO        IS 'Indicador de estado A(Activo), I(Inactivo)';
COMMENT ON COLUMN CRITERIO.USRCREACION      IS 'Usuario de creacion';
COMMENT ON COLUMN CRITERIO.FECCREACION      IS 'Fecha de creacion';
COMMENT ON COLUMN CRITERIO.USRMODIFICACION  IS 'Usuario de modificacion';
COMMENT ON COLUMN CRITERIO.FECMODIFICACION  IS 'Fecha de modificación';

ALTER TABLE CRITERIO ADD CONSTRAINT PK_CRITERIO 
  PRIMARY KEY (IDECRITERIO) 
;

ALTER TABLE CRITERIO MODIFY TIPMEDICION CONSTRAINT NN_CRITERIO_TIPMEDICION NOT NULL ;

ALTER TABLE CRITERIO MODIFY TIPCRITERIO CONSTRAINT NN_CRITERIO_TIPCRITERIO NOT NULL ;

ALTER TABLE CRITERIO MODIFY TIPMODO CONSTRAINT NN_CRITERIO_TIPMODO NOT NULL ;

ALTER TABLE CRITERIO MODIFY TIPCALIFICACION CONSTRAINT NN_CRITERIO_TIPCALIFICACION NOT NULL ;


