--INSERTAR TIPO DE VIAS TABLA DETALLE GENERAL - 
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (1,1,'TIPOVIA','01','AVENIDA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (2,1,'TIPOVIA','02','JIRÓN');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (3,1,'TIPOVIA','03','CALLE');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (4,1,'TIPOVIA','04','PASAJE');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (5,1,'TIPOVIA','05','ALAMEDA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (6,1,'TIPOVIA','06','MALECON');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (7,1,'TIPOVIA','07','OVALO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (8,1,'TIPOVIA','08','PARQUE');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (9,1,'TIPOVIA','09','PLAZA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (10,1,'TIPOVIA','10','CARRETERA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (11,1,'TIPOVIA','11','TROCHA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (12,1,'TIPOVIA','12','CAMINO RURAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (13,1,'TIPOVIA','13','BAJADA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (14,1,'TIPOVIA','14','GALERIA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (15,1,'TIPOVIA','15','PROLONGACIÓN');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (16,1,'TIPOVIA','16','PASEO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (17,1,'TIPOVIA','17','PLAZUELA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (18,1,'TIPOVIA','18','PORTAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (19,1,'TIPOVIA','19','CAMINO AFIRMADO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (20,1,'TIPOVIA','20','TROCHA CARROZABLE');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (21,1,'TIPOVIA','21','OTROS');
  

--INSERTAR DATOS DE TIPOS DE ZONAS

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (23,2,'TIPOZONA','01','URBANIZACIÓN');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (24,2,'TIPOZONA','02','PUEBLO JOVEN');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (25,2,'TIPOZONA','03','UNIDAD VECINAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (24,2,'TIPOZONA','04','CONJUNTO HABITACIONAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (25,2,'TIPOZONA','05','ASENTAMIENTO HUMANO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (26,2,'TIPOZONA','06','COOPERATIVA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (27,2,'TIPOZONA','07','RESIDENCIAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (28,2,'TIPOZONA','08','ZONA INDUSTRIAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (29,2,'TIPOZONA','09','GRUPO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (30,2,'TIPOZONA','10','CASERÍO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (31,2,'TIPOZONA','11','FUNDO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (32,2,'TIPOZONA','12','OTROS');

--INSERTAR DATOS DEESTADOS CIVILES

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (33,3,'ESTADOCIVIL','01','SOLTERO/A');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (34,3,'ESTADOCIVIL','02','CASADO/A');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (35,3,'ESTADOCIVIL','03','VIUDO/A');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (36,3,'ESTADOCIVIL','04','DIVORCIADO/A');

--INSERTAR DATOS DE IDENTIFICADOR DE SEXO

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (37,4,'SEXO','1','MASCULLINO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (38,4,'SEXO','2','FEMENINO');

--INSERTAR DATOS TIPO DE DOCUMENTOS
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (39,5,'TIPODOCUMENTO','1','DNI');

--INSERTAR DATOS TIPO DE NACIONALIDAD
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (40,6,'NACIONALIDAD','1','PERUANA');

--INSERTAR DATOS TIPO DISPONIBILIDAD TRABAJO
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (50,8,'TIPDISPTRABAJO','01','INMEDIATA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (51,8,'TIPDISPTRABAJO','02','15 DIAS');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (52,8,'TIPDISPTRABAJO','03','A TRATAR');

--INSERTAR DATOS TIPO DISPONIBILIDAD HORARIOS
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (53,9,'TIPDISPHORARIO','01','ROTATIVO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (54,9,'TIPDISPHORARIO','02','FIJO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (55,9,'TIPDISPHORARIO','03','DIAZ');

--INSERTAR DATOS DE TIPO HORARIO

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (56,10,'TIPHORARIO','01','MAÑANA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (57,10,'TIPHORARIO','01','TARDE');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (58,10,'TIPHORARIO','01','MOCHE');

--INSERTAR DATOS DE TIPO PARIENTES SEDES
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (59,10,'TIPPARIENTESEDE','01','CHSP-SURCO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (60,10,'TIPPARIENTESEDE','01','CHSP-SAN MIGUEL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (61,10,'TIPPARIENTESEDE','01','CHSP-SAN JUAN');

--INSERTAR DATOS DE PRETENSIONES SALARIALES
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (62,11,'TIPSALARIO','01','MENOS DE S/.1000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (63,11,'TIPSALARIO','01','DE S/.1000 A S/.2000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (64,11,'TIPSALARIO','01','DE S/.2000 A S/.3000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (65,11,'TIPSALARIO','01','DE S/.3000 A S/.4000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (66,11,'TIPSALARIO','01','DE S/.4000 A S/.5000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (67,11,'TIPSALARIO','01','DE S/.5000 A S/.6000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (68,11,'TIPSALARIO','01','MAS DE S/.6000');
