ALTER TABLE CHSPRP.DISCAPACIDAD_PERSONA
 DROP PRIMARY KEY CASCADE;

DROP TABLE CHSPRP.DISCAPACIDAD_PERSONA CASCADE CONSTRAINTS;

CREATE TABLE CHSPRP.DISCAPACIDAD_PERSONA
(
  IDEDISCAPACIDADPERSONA  NUMBER(8)             NOT NULL,
  IDEPERSONA              NUMBER(8),
  TIPODISCAPA             VARCHAR2(3 CHAR),
  DESTIPDISCA             VARCHAR2(50 CHAR),
  USRCREACION             VARCHAR2(15 CHAR),
  FCHCREACION             DATE,
  USRMODIFICA             VARCHAR2(15 CHAR),
  FCH_MODIFICA            DATE
)
TABLESPACE CHSP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CHSPRP.PK_DISCAPACIDAD_POSTULANTE ON CHSPRP.DISCAPACIDAD_PERSONA
(IDEDISCAPACIDADPERSONA)
LOGGING
TABLESPACE CHSP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CHSPRP.DISCAPACIDAD_PERSONA ADD (
  CONSTRAINT PK_DISCAPACIDAD_POSTULANTE
  PRIMARY KEY
  (IDEDISCAPACIDADPERSONA)
  USING INDEX CHSPRP.PK_DISCAPACIDAD_POSTULANTE);

ALTER TABLE CHSPRP.DISCAPACIDAD_PERSONA ADD (
  CONSTRAINT FK_DISCAPACIDAD_POS_POSTULANTE 
  FOREIGN KEY (IDEPERSONA) 
  REFERENCES CHSPRP.PERSONA (IDEPERSONA));

