

CREATE TABLE CONOGEN_POSTULANTE
(
  IDECONOGENPOSTULANTE  NUMBER(8) NOT NULL,    --  Identificador de conocimientos generales de la persona 
  IDEPOSTULANTE         NUMBER(8) NULL,    --  Identificador de la persona(Postulante) 
  TIPCONOFIMATICA       VARCHAR2(3) NULL,    --  Código del tipo de conocimiento 
  TIPNOMOFIMATICA       VARCHAR2(3) NULL,    --  Código del conocimiento general 
  TIPIDIOMA             VARCHAR2(3) NULL,
  TIPCONOCIDIOMA        VARCHAR2(3) NULL,
  TIPCONOCGENERALES     NVARCHAR2(3) NULL,
  TIPNOMCONOCGRALES     VARCHAR2(3) NULL,
  NOMCONOCGRALES        VARCHAR2(50) NULL,
  TIPNIVELCONOCIMIENTO  VARCHAR2(3) NULL,
  INDCERTIFICACION      VARCHAR2(1) NULL,
  USRCREACION           VARCHAR2(15) NULL,    
  FECCREACION           DATE NULL,   
  USRMODIFICACION       VARCHAR2(15) NULL,
  FECMODIFICACION       DATE NULL    
)
;



CREATE TABLE DISCAPACIDAD_POSTULANTE
(
  IDEDISCAPACIDADPOSTULANTE  NUMBER(8) NOT NULL,    --  Identificador de discapacidad por cargo 
  IDEPOSTULANTE              NUMBER(8) NULL,    --  Identificador de la persona 
  TIPODISCAPACIDAD           VARCHAR2(3) NULL,    --  Código del tipo de discapacidad 
  DESDISCAPACIDAD            VARCHAR2(50) NULL,    
  USRCREACION                VARCHAR2(15) NULL,   
  FECCREACION                DATE NULL,    
  USRMODIFICACION            VARCHAR2(15) NULL,   
  FECMODIFICACION            DATE NULL   
)
;

CREATE TABLE ESTUDIOS_POSTULANTE
(
  IDEESTUDIOSPOSTULANTE  NUMBER(8) NOT NULL,     
  IDEPOSTULANTE          NUMBER(8) NULL,   
  TIPTIPOINSTITUCION     VARCHAR2(3) NOT NULL,   
  TIPNOMINSTITUCION      VARCHAR2(100) NOT NULL,
  NOMINSTITUCION         VARCHAR2(100) NULL,
  TIPAREA                VARCHAR2(3) NULL,   
  TIPEDUCACION           VARCHAR2(3) NOT NULL,    
  TIPNIVELALCANZADO      VARCHAR2(3) NOT NULL,    
  FECESTUDIOINICIO       DATE NOT NULL,     
  FECESTUDIOFIN          DATE NULL,    
  INDESTACTUALMENTE      VARCHAR2(1) NULL,     
  USRCREACION            VARCHAR2(15) NULL,     
  FECCREACION            DATE NULL,     
  USRMODIFICACION        VARCHAR2(50) NULL,     
  FECMODIFICACION        DATE NULL     
)
;


CREATE TABLE EXP_POSTULANTE
(
  IDEEXPPOSTULANTE     NUMBER(8) NOT NULL,    
  IDEPOSTULANTE        NUMBER(8) NULL,
  NOMEMPRESA           VARCHAR2(100) NOT NULL,    
  TIPCARGOTRABAJO      VARCHAR2(3) NOT NULL,     
  FECTRABINICIO        DATE NOT NULL,     
  FECTRABFIN           DATE NULL,    
  INDTRABACTUALMENTE   VARCHAR2(1) NULL,
  TIEMPOSERVICIO       VARCHAR2(20) NULL,
  TIPMOTIVOCESE        VARCHAR2(3) NULL,    
  NOMREFERENTE         VARCHAR2(100) NOT NULL,
  NUMTELEFMOVILREF     NUMBER(9) NULL,
  TIPCARGOTRABAJOREF   VARCHAR2(3) NOT NULL,
  NUMTELEFONOFIJOINST  NUMBER(9) NOT NULL,
  NUMANEXOINST         NUMBER(6) NULL,
  USRCREACION          VARCHAR2(15) NULL,    
  FECCREACION          DATE NULL,    
  USRMODIFICACION      VARCHAR2(15) NULL,     
  FECMODIFICACION      DATE NULL    
)
;



CREATE TABLE PARIENTES_POSTULANTE
(
  IDEPARIENTESPOSTULANTE  NUMBER(8) NOT NULL,   
  IDEPOSTULANTE           NUMBER(8) NULL,    
  APEMATERNO              VARCHAR2(100) NULL,     
  APEPATERNO              VARCHAR2(50) NULL,     
  NOMBRES                 VARCHAR2(50) NULL,     
  TIPVINCULO              VARCHAR2(3) NULL,     
  FECNACIMIENTO           DATE NULL,     
  USRCREACION             VARCHAR2(15) NULL,     
  FECCREACION             DATE NULL,     
  USRMODIFICACION         VARCHAR2(15) NULL,     
  FECMODIFICACION         DATE NULL     
)
;



CREATE TABLE POSTULANTE
(
  IDEPERSONA        NUMBER(8) NOT NULL,    
  TIPDOCUMENTO      VARCHAR2(3) NOT NULL,     
  NUMDOCUMENTO      VARCHAR2(8) NOT NULL,    
  APEPATERNO        VARCHAR2(25) NOT NULL,    
  APEMATERNO        VARCHAR2(25) NOT NULL,   
  PRINOMBRE         VARCHAR2(25) NOT NULL,    
  SEGNOMBRE         VARCHAR2(25) NULL,    
  TIPNACIONALIDAD   VARCHAR2(3) NOT NULL,    
  FECNACIMIENTO     DATE NOT NULL,     
  INDSEXO           VARCHAR2(1) NOT NULL,
  NUMLICENCIA       VARCHAR2(9) NULL,     
  TIPESTCIVIL       VARCHAR2(3) NOT NULL,    
  OBSERVACION       VARCHAR2(255) NULL,
  TIPVIA            VARCHAR2(3) NOT NULL,    
  NOMVIA            VARCHAR2(100) NOT NULL,    
  NUMDIRECCION      NUMBER(4) NULL,      
  INTERIOR          NUMBER(3) NULL,    
  TIPDISTRITO       VARCHAR2(3) NOT NULL,
  MANZANA           VARCHAR2(2) NULL,
  LOTE              VARCHAR2(3) NULL,
  CORREO            VARCHAR2(50) NOT NULL,    
  BLOQUE            VARCHAR2(3) NULL,
  ETAPA             VARCHAR2(3) NULL,
  IDEUBIGEO         NUMBER(6) NULL,     
  TELMOVIL          NUMBER(9) NOT NULL,   
  TIPZONA           VARCHAR2(3) NULL,     
  TELFIJO           NUMBER(8) NULL,   
  NOMZONA           VARCHAR2(100) NULL,    
  REFERENCIA        VARCHAR2(100) NOT NULL,     
  FOTOPOSTULANTE    VARCHAR2(255) NULL,     
  TIPSALARIO        NUMBER(8) NOT NULL,    
  TIPDISPTRABAJO    VARCHAR2(3) NOT NULL,      
  TIPDISPHORARIO    VARCHAR2(3) NOT NULL,    
  TIPHORARIO        VARCHAR2(3) NULL,     
  INDREUBIINTEPAIS  VARCHAR2(1) NULL,     
  INDPARIENTECHSP   VARCHAR2(1) NULL,    
  TIPPARIENTESEDE   VARCHAR2(3) NULL,   
  PARIENTENOMBRE    VARCHAR2(100) NULL,    
  PARIENTECARGO     VARCHAR2(50) NULL,     
  TIPCOMOSEENTERO   VARCHAR2(3) NOT NULL,   
  DESOTROMEDIO      VARCHAR2(50) NULL,     
  INDTREGISTRO      VARCHAR2(1) NULL,    
  USRCREACION       VARCHAR2(15) NULL,     
  FECCREACION       DATE NULL,    
  USRMODIFICACION   VARCHAR2(15) NULL,    
  FECMODIFICACION   DATE NULL    
)
;

ALTER TABLE CONOGEN_POSTULANTE ADD CONSTRAINT PK_CONOGEN_POSTULANTE 
  PRIMARY KEY (IDECONOGENPOSTULANTE) 
 USING INDEX 
;

ALTER TABLE DISCAPACIDAD_POSTULANTE ADD CONSTRAINT PK_DISCAPACIDAD_POSTULANTE 
  PRIMARY KEY (IDEDISCAPACIDADPOSTULANTE) 
 USING INDEX 
;

ALTER TABLE ESTUDIOS_POSTULANTE ADD CONSTRAINT PK_ESTUDIOS_POSTULANTE 
  PRIMARY KEY (IDEESTUDIOSPOSTULANTE) 
 USING INDEX 
;

ALTER TABLE EXP_POSTULANTE ADD CONSTRAINT PK_EXPLAB_POSTULANTE 
  PRIMARY KEY (IDEEXPPOSTULANTE) 
 USING INDEX 
;

ALTER TABLE PARIENTES_POSTULANTE ADD CONSTRAINT PK_PARIENTES_POSTULANTE 
  PRIMARY KEY (IDEPARIENTESPOSTULANTE) 
 USING INDEX 
;

ALTER TABLE POSTULANTE ADD CONSTRAINT PK_POSTULANTE 
  PRIMARY KEY (IDEPERSONA) 
 USING INDEX 
;


ALTER TABLE POSTULANTE
  ADD CONSTRAINT UQ_POSTULANTE_CORREO UNIQUE (CORREO)
 USING INDEX 
;

ALTER TABLE POSTULANTE
  ADD CONSTRAINT UQ_POSTULANTE_NUMDOCUMENTO UNIQUE (NUMDOCUMENTO)
 USING INDEX 
;


ALTER TABLE CONOGEN_POSTULANTE ADD CONSTRAINT FK_CONOGEN_POSTULAN_POSTULANTE 
  FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPERSONA)
;

ALTER TABLE DISCAPACIDAD_POSTULANTE ADD CONSTRAINT FK_DISCAPACIDAD_POS_POSTULANTE 
  FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPERSONA)
;

ALTER TABLE ESTUDIOS_POSTULANTE ADD CONSTRAINT FK_ESTUDIOS_POSTULA_POSTULANTE 
  FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPERSONA)
;

ALTER TABLE EXP_POSTULANTE ADD CONSTRAINT FK_EXPLAB_POSTULANT_POSTULANTE 
  FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPERSONA)
;

ALTER TABLE PARIENTES_POSTULANTE ADD CONSTRAINT FK_PARIENTES_POSTUL_POSTULANTE 
  FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPERSONA)
;
