CREATE OR REPLACE VIEW LISTA_SOLICITUD_NUEVO_CARGO AS
SELECT SN.IDESOLNUEVOCARGO, PR_INTRANET.FN_ESTADO_SOLICITUD(SN.IDESOLNUEVOCARGO,'N') ESTADO,SN.CODCARGO,(SELECT C.IDECARGO FROM CARGO C WHERE C.CODCARGO = SN.CODCARGO) IDECARGO ,SN.NOMBRE ,DE.IDEDEPENDENCIA,
       DE.NOMDEPENDENCIA,DP.IDEDEPARTAMENTO ,DP.NOMDEPARTAMENTO, AR.IDEAREA,AR.NOMAREA,
       SN.NUMPOSICIONES, SN.FECCREACION,R.IDROL ,R.DSCROL ,
       (PR_REQUERIMIENTOS.FN_NOMRESPONS_SOL(SN.IDESOLNUEVOCARGO,'N')) NOMRESPONSABLE, LS.TIPETAPA,(PR_INTRANET.FN_VALOR_GENERAL('ETAPA',LS.TIPETAPA)) TETAPA
  FROM SOLNUEVO_CARGO SN, AREA AR, DEPARTAMENTO DP, DEPENDENCIA DE , LOGSOLNUEVO_CARGO LS LEFT JOIN ROL R ON (R.IDROL = LS.ROLRESPONSABLE)
  WHERE SN.IDEAREA = AR.IDEAREA
  AND AR.IDEDEPARTAMENTO = DP.IDEDEPARTAMENTO
  AND DP.IDEDEPENDENCIA = DE.IDEDEPENDENCIA
  AND LS.IDESOLNUEVOCARGO = SN.IDESOLNUEVOCARGO
  AND LS.FECSUCESO = (SELECT MAX (FECSUCESO)
                           FROM  LOGSOLNUEVO_CARGO LN
                           WHERE LN.IDESOLNUEVOCARGO = SN.IDESOLNUEVOCARGO)
;
