CREATE OR REPLACE VIEW LISTA_SOLICITUD_NUEVO_CARGO AS
SELECT SN.IDESOLNUEVOCARGO, SN.ESTACTIVO, SN.CODCARGO, SN.NOMBRE ,DE.IDEDEPENDENCIA,
       DE.NOMDEPENDENCIA,DP.IDEDEPARTAMENTO ,DP.NOMDEPARTAMENTO, AR.IDEAREA,AR.NOMAREA,
       SN.NUMPOSICIONES, SN.FECCREACION,R.IDROL ,R.DSCROL ,
       (PR_REQUERIMIENTOS.FN_NOMRESPONS_SOL(SN.IDESOLNUEVOCARGO)) NOMRESPONSABLE, LS.TIPETAPA,(PR_INTRANET.FN_VALOR_GENERAL('TIPOETAPA',LS.TIPETAPA)) TETAPA, LS.TIPSUCESO , (PR_INTRANET.FN_VALOR_GENERAL('TIPOSUCESO',LS.TIPSUCESO)) ETAPA 
  FROM SOLNUEVO_CARGO SN, AREA AR, DEPARTAMENTO DP, DEPENDENCIA DE , LOGSOLNUEVO_CARGO LS, ROL R
  WHERE SN.IDEAREA = AR.IDEAREA
  AND AR.IDEDEPARTAMENTO = DP.IDEDEPARTAMENTO
  AND DP.IDEDEPENDENCIA = DE.IDEDEPENDENCIA
  AND LS.IDESOLNUEVOCARGO = SN.IDESOLNUEVOCARGO
  AND R.IDROL = LS.ROLRESPONSABLE
  AND LS.FECSUCESO = (SELECT MAX (FECSUCESO)
                           FROM  LOGSOLNUEVO_CARGO LN
                           WHERE LN.IDESOLNUEVOCARGO = SN.IDESOLNUEVOCARGO)
;
