CREATE OR REPLACE VIEW UBIGEODESCRIPCION AS
 SELECT  UBIG.IDEUBIGEO IDUBIGEO, UBIG.NOMBRE DISTRITO, U.IDEUBIGEO IDUBIGEOPROV, U.NOMBRE PROVINCIA,UBI.IDEUBIGEO IDUBIGEODEPAR, UBI.NOMBRE DEPARTAMENT 
 FROM UBIGEO U , (SELECT * FROM UBIGEO UB WHERE UB.IDEUBIGEOPADRE IS NULL) UBI , (SELECT * FROM UBIGEO U WHERE U.IDEUBIGEOPADRE IS NOT NULL) UBIG
 WHERE U.IDEUBIGEOPADRE IS NOT NULL
 AND U.IDEUBIGEOPADRE = UBI.IDEUBIGEO
 AND UBIG.IDEUBIGEOPADRE = U.IDEUBIGEO;
