--INSERTAR TIPO DE VIAS TABLA DETALLE GENERAL - 
INSERT INTO GENERAL(IDEGENERAL,TIPTABLA,DESCRIPCION,TIPDATO,LONCAMPO,USRCREACION,FECCREACION) VALUES(1,'TIPOVIA','Tipo de via','VARCHAR2',2,'SYSTEM',SYSDATE);

INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'AV','AVENIDA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'JR','JIRÓN','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'CL','CALLE','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'PA','PASAJE','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'AL','ALAMEDA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'ML','MALECON','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'OV','OVALO','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'PQ','PARQUE','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'PL','PLAZA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'CT','CARRETERA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'TR','TROCHA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'CR','CAMINO RURAL','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'BA','BAJADA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'GA','GALERIA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'PL','PROLONGACIÓN','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'PS','PASEO','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'PZ','PLAZUELA','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'PO','PORTAL','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'CA','CAMINO AFIRMADO','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'TC','TROCHA CARROZABLE','A');
INSERT INTO DETALLE_GENERAL (IDEGENERAL,VALOR,DESCRIPCION,INDACTIVO) VALUES (1,'OT','OTROS','A');
  

--INSERTAR DATOS DE TIPOS DE ZONAS

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (23,2,'TIPOZONA','01','URBANIZACIÓN');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (24,2,'TIPOZONA','02','PUEBLO JOVEN');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (25,2,'TIPOZONA','03','UNIDAD VECINAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (24,2,'TIPOZONA','04','CONJUNTO HABITACIONAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (25,2,'TIPOZONA','05','ASENTAMIENTO HUMANO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (26,2,'TIPOZONA','06','COOPERATIVA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (27,2,'TIPOZONA','07','RESIDENCIAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (28,2,'TIPOZONA','08','ZONA INDUSTRIAL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (29,2,'TIPOZONA','09','GRUPO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (30,2,'TIPOZONA','10','CASERÍO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (31,2,'TIPOZONA','11','FUNDO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (32,2,'TIPOZONA','12','OTROS');

--INSERTAR DATOS DEESTADOS CIVILES

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (33,3,'ESTADOCIVIL','01','SOLTERO/A');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (34,3,'ESTADOCIVIL','02','CASADO/A');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (35,3,'ESTADOCIVIL','03','VIUDO/A');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (36,3,'ESTADOCIVIL','04','DIVORCIADO/A');

--INSERTAR DATOS DE IDENTIFICADOR DE SEXO

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (37,4,'SEXO','1','MASCULLINO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (38,4,'SEXO','2','FEMENINO');

--INSERTAR DATOS TIPO DE DOCUMENTOS
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (39,5,'TIPODOCUMENTO','1','DNI');

--INSERTAR DATOS TIPO DE NACIONALIDAD
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (40,6,'NACIONALIDAD','1','PERUANA');

--INSERTAR DATOS TIPO DISPONIBILIDAD TRABAJO
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (50,8,'TIPDISPTRABAJO','01','INMEDIATA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (51,8,'TIPDISPTRABAJO','02','15 DIAS');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (52,8,'TIPDISPTRABAJO','03','A TRATAR');

--INSERTAR DATOS TIPO DISPONIBILIDAD HORARIOS
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (53,9,'TIPDISPHORARIO','01','ROTATIVO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (54,9,'TIPDISPHORARIO','02','FIJO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (55,9,'TIPDISPHORARIO','03','DIAZ');

--INSERTAR DATOS DE TIPO HORARIO

INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (56,10,'TIPHORARIO','01','MAÑANA');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (57,10,'TIPHORARIO','01','TARDE');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (58,10,'TIPHORARIO','01','MOCHE');

--INSERTAR DATOS DE TIPO PARIENTES SEDES
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (59,10,'TIPPARIENTESEDE','01','CHSP-SURCO');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (60,10,'TIPPARIENTESEDE','01','CHSP-SAN MIGUEL');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (61,10,'TIPPARIENTESEDE','01','CHSP-SAN JUAN');

--INSERTAR DATOS DE PRETENSIONES SALARIALES
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (62,11,'TIPSALARIO','01','MENOS DE S/.1000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (63,11,'TIPSALARIO','01','DE S/.1000 A S/.2000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (64,11,'TIPSALARIO','01','DE S/.2000 A S/.3000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (65,11,'TIPSALARIO','01','DE S/.3000 A S/.4000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (66,11,'TIPSALARIO','01','DE S/.4000 A S/.5000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (67,11,'TIPSALARIO','01','DE S/.5000 A S/.6000');
INSERT INTO DETALLE_GENERAL (IDEDETALLEGENERAL,IDEGENERAL,TIPTABLA,VALOR,DESCRIPCION) VALUES (68,11,'TIPSALARIO','01','MAS DE S/.6000');
