DROP TABLE DISCAPACIDAD_POSTULANTE CASCADE CONSTRAINTS;

CREATE TABLE DISCAPACIDAD_POSTULANTE
(
  IDEDISCAPACIDADPOSTULANTE  NUMBER(8), 
  IDEPOSTULANTE              NUMBER(8), 
  TIPODISCAPACIDAD           VARCHAR2(3), 
  DESDISCAPACIDAD            VARCHAR2(50), 
  ESTACTIVO                  VARCHAR2(1), 
  USRCREACION                VARCHAR2(15), 
  FECCREACION                DATE, 
  USRMODIFICACION            VARCHAR2(15), 
  FECMODIFICACION            DATE 
)
;

COMMENT ON TABLE DISCAPACIDAD_POSTULANTE IS 'Tabla de discapacidad de la persona';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.IDEDISCAPACIDADPOSTULANTE  IS 'Identificador de discapacidad por cargo';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.IDEPOSTULANTE              IS 'Identificador de la persona';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.TIPODISCAPACIDAD           IS 'Código del tipo de discapacidad';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.DESDISCAPACIDAD            IS 'Descripción del la discapacidad';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.ESTACTIVO                  IS 'Indicador de estado A(activo) y I(inactivo)';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.USRCREACION                IS 'Usuario que creó el registro';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.FECCREACION                IS 'Fecha de creación del registro';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.USRMODIFICACION            IS 'Usuario que modificó el registro';
COMMENT ON COLUMN DISCAPACIDAD_POSTULANTE.FECMODIFICACION            IS 'Fecha de modificación del registro';


ALTER TABLE DISCAPACIDAD_POSTULANTE ADD CONSTRAINT DISCAPACIDAD_POSTULANTE_PK PRIMARY KEY (IDEDISCAPACIDADPOSTULANTE);

ALTER TABLE DISCAPACIDAD_POSTULANTE ADD CONSTRAINT DISCAPACIDAD_POS_POSTULANTE_FK FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPOSTULANTE);


ALTER TABLE DISCAPACIDAD_POSTULANTE MODIFY ESTACTIVO CONSTRAINT DISCAP_POST_ESTACTIVO_NN NOT NULL;
