DROP TABLE ESTUDIOS_POSTULANTE CASCADE CONSTRAINTS;

CREATE TABLE ESTUDIOS_POSTULANTE
(
  IDEESTUDIOSPOSTULANTE  NUMBER(8), 
  IDEPOSTULANTE          NUMBER(8), 
  TIPTIPOINSTITUCION     VARCHAR2(3), 
  TIPNOMINSTITUCION      VARCHAR2(100),
  NOMINSTITUCION         VARCHAR2(100),
  TIPAREA                VARCHAR2(3), 
  TIPEDUCACION           VARCHAR2(3), 
  TIPNIVELALCANZADO      VARCHAR2(3), 
  FECESTUDIOINICIO       DATE, 
  FECESTUDIOFIN          DATE, 
  INDESTACTUALMENTE      VARCHAR2(1), 
  ESTACTIVO              VARCHAR2(1), 
  USRCREACION            VARCHAR2(15), 
  FECCREACION            DATE, 
  USRMODIFICACION        VARCHAR2(50), 
  FECMODIFICACION        DATE 
)
;

COMMENT ON TABLE ESTUDIOS_POSTULANTE IS 'Tabla de estudios de la persona';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.IDEESTUDIOSPOSTULANTE  IS 'Identificador de estudios del postulante';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.IDEPOSTULANTE          IS 'Identificador de la persona (postulante)';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.TIPTIPOINSTITUCION     IS 'Institución';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.TIPAREA                IS 'Área de estudios';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.TIPEDUCACION           IS 'Tipo de educación';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.TIPNIVELALCANZADO      IS 'Nivel alcanzado';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.FECESTUDIOINICIO       IS 'Fecha de inicio de estudios';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.FECESTUDIOFIN          IS 'Fecha de fin de estudios';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.INDESTACTUALMENTE      IS 'Indicador en caso se encuentre estudiando';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.ESTACTIVO              IS 'Indicador de estado A(activo) y I(inactivo)';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.USRCREACION            IS 'Usuario que creó el registro';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.FECCREACION            IS 'Fecha de creación del registro';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.USRMODIFICACION        IS 'Usuario que modificó el registro';
COMMENT ON COLUMN ESTUDIOS_POSTULANTE.FECMODIFICACION        IS 'Fecha de modificación del registro';


ALTER TABLE ESTUDIOS_POSTULANTE ADD CONSTRAINT ESTUDIOS_POSTULANTE_PK PRIMARY KEY (IDEESTUDIOSPOSTULANTE);

ALTER TABLE ESTUDIOS_POSTULANTE ADD CONSTRAINT ESTUDIOS_POSTULA_POSTULANTE_FK FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPOSTULANTE);


ALTER TABLE ESTUDIOS_POSTULANTE MODIFY TIPTIPOINSTITUCION CONSTRAINT ESTUD_POST_TIPTIPINST_NN NOT NULL ;

ALTER TABLE ESTUDIOS_POSTULANTE MODIFY TIPNOMINSTITUCION CONSTRAINT ESTUD_POST_TIPNOMINST_NN NOT NULL ;

ALTER TABLE ESTUDIOS_POSTULANTE MODIFY TIPEDUCACION CONSTRAINT ESTUD_POST_TIPEDUCA_NN NOT NULL ;

ALTER TABLE ESTUDIOS_POSTULANTE MODIFY TIPNIVELALCANZADO CONSTRAINT ESTUD_POST_TIPNIVALCANZ_NN NOT NULL ;

ALTER TABLE ESTUDIOS_POSTULANTE MODIFY FECESTUDIOINICIO CONSTRAINT ESTUD_POST_FECESTINI_NN NOT NULL ;
