DROP TABLE EXP_POSTULANTE CASCADE CONSTRAINTS;

CREATE TABLE EXP_POSTULANTE
(
  IDEEXPPOSTULANTE     NUMBER(8),
  IDEPOSTULANTE        NUMBER(8),
  NOMEMPRESA           VARCHAR2(100), 
  TIPCARGOTRABAJO      VARCHAR2(3), 
  NOMCARGOTRABAJO	   VARCHAR2(50),	
  FECTRABINICIO        DATE, 
  FECTRABFIN           DATE, 
  INDTRABACTUALMENTE   VARCHAR2(1),
  TIEMPOSERVICIO       VARCHAR2(20),
  TIPMOTIVOCESE        VARCHAR2(3), 
  NOMREFERENTE         VARCHAR2(100),
  NUMTELEFMOVILREF     NUMBER(9),
  CORREOREFERENTE	   VARCHAR2(50),
  TIPCARGOTRABAJOREF   VARCHAR2(3),
  NUMTELEFONOFIJOINST  NUMBER(9),
  NUMANEXOINST         NUMBER(6),
  ESTACTIVO            VARCHAR2(1), 
  USRCREACION          VARCHAR2(15), 
  FECCREACION          DATE, 
  USRMODIFICACION      VARCHAR2(15), 
  FECMODIFICACION      DATE 
)
;

COMMENT ON TABLE EXP_POSTULANTE IS 'Tabla de experiencia laboral de la persona';
COMMENT ON COLUMN EXP_POSTULANTE.IDEEXPPOSTULANTE     IS 'Identificador de experiencia laboral del postulante';
COMMENT ON COLUMN EXP_POSTULANTE.NOMEMPRESA           IS 'Empresa en la que laboró';
COMMENT ON COLUMN EXP_POSTULANTE.TIPCARGOTRABAJO      IS 'Cargo desempeñado';
COMMENT ON COLUMN EXP_POSTULANTE.FECTRABINICIO        IS 'Fecha de inicio';
COMMENT ON COLUMN EXP_POSTULANTE.FECTRABFIN           IS 'Fecha de fin';
COMMENT ON COLUMN EXP_POSTULANTE.TIPMOTIVOCESE        IS 'Motivo de cese';
COMMENT ON COLUMN EXP_POSTULANTE.ESTACTIVO            IS 'Indicador de estado A(activo) y I(inactivo)';
COMMENT ON COLUMN EXP_POSTULANTE.USRCREACION          IS 'Usuario que creó el registro';
COMMENT ON COLUMN EXP_POSTULANTE.FECCREACION          IS 'Fecha de creación del registro';
COMMENT ON COLUMN EXP_POSTULANTE.USRMODIFICACION      IS 'Usuario que modificó el registro';
COMMENT ON COLUMN EXP_POSTULANTE.FECMODIFICACION      IS 'Fecha de modificación del registro';

ALTER TABLE EXP_POSTULANTE ADD CONSTRAINT EXPLAB_POSTULANTE_PK PRIMARY KEY (IDEEXPPOSTULANTE);

ALTER TABLE EXP_POSTULANTE ADD CONSTRAINT EXPLAB_POSTULANT_POSTULANTE_FK FOREIGN KEY (IDEPOSTULANTE) REFERENCES POSTULANTE (IDEPOSTULANTE);


ALTER TABLE EXP_POSTULANTE MODIFY NOMEMPRESA CONSTRAINT EXP_POSTU_NOMEMPRESA_NN NOT NULL;

ALTER TABLE EXP_POSTULANTE MODIFY TIPCARGOTRABAJO CONSTRAINT EXP_POSTU_TIPCARGOTRABAJO_NN NOT NULL;

ALTER TABLE EXP_POSTULANTE MODIFY FECTRABINICIO CONSTRAINT EXP_POSTU_FECTRABINICIO_NN NOT NULL;

ALTER TABLE EXP_POSTULANTE MODIFY NOMREFERENTE CONSTRAINT EXP_POSTU_NOMREFERENTE_NN NOT NULL;

ALTER TABLE EXP_POSTULANTE MODIFY TIPCARGOTRABAJOREF CONSTRAINT EXP_POSTU_TIPCARGOREF_NN NOT NULL;

ALTER TABLE EXP_POSTULANTE MODIFY NUMTELEFONOFIJOINST CONSTRAINT EXP_POSTU_NUMTELFIJOINST_NN NOT NULL;

ALTER TABLE EXP_POSTULANTE MODIFY ESTACTIVO CONSTRAINT EXP_POSTU_ESTACTIVO_NN NOT NULL;
